### ISSUE TITLE
Write CSS according to box model order

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#109]

**Comment by gpxl-dev** [comment]
To me it feels an IDE or linting plugin should be able to handle this for us?
@piersss I believe this was your point - is there a strict order that you normally stick to, or do you just go with

- structural / layout properties
- display only properties

**Comment by piersss** [comment]
No strict order, just according to importance of impact to box-model. So `display` should be high and `background` should be low on the list.

**Comment by piersss** [comment]
This is going as planned so this ticket can be removed.
