### ISSUE TITLE
New toolbar and content modals

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#127]
https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/New-AirSwap-Website?node-id=1478%3A3790

**Comment by Japlito** [comment]
As we discussed in Discord, this version came out and is now up for review

https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/New-AirSwap-Website?node-id=1478%3A3790
