### ISSUE TITLE
Bookmark warning

### ISSUE THREAD

**Issue by gregplumbly** [airswap/airswap-web#14]
Optimally the warning pushes down the content of the entire app to keep existing padding

https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/New-AirSwap-Website?node-id=1261%3A2907

**Comment by gpxl-dev** [comment]
Could you elaborate on this one? :)

**Comment by gregplumbly** [comment]
Apologies, some of these started life as placeholders. Will go through and expand in the next few days.

For this one, I noticed many DeFi sites use a reminder banner for users to bookmark the site, rather than risk following search engine links. Normally they can be dismissed. 
![aave](https://user-images.githubusercontent.com/4796/121259711-f6bf0080-c89f-11eb-8aff-7a81c046a64f.jpg)

**Comment by gregplumbly** [comment]
please enjoy cow swap dark mode. 
![cow-swap dark mode](https://user-images.githubusercontent.com/4796/121260063-63d29600-c8a0-11eb-943c-7cfbc3f1511b.jpg)

**Comment by NassK44** [comment]
I created a first draft of it. We can obv work on the wording. Let me know what you think about it. My idea was, that it pushes down the Darkmode Switch and  AirSwap Logo, but after being dismissed, those elements return to their normal position. 

Also created an alternative grey version which looks a bit more subtle.

![bookmark warning solo](https://user-images.githubusercontent.com/86799270/124482322-71007900-dda9-11eb-8037-d992b945c458.png)
![Bookmark warning _alt](https://user-images.githubusercontent.com/86799270/124482326-71990f80-dda9-11eb-9f52-cc0a9c0090d5.jpg)
![Bookmark warning](https://user-images.githubusercontent.com/86799270/124482328-71990f80-dda9-11eb-94f4-9b3e64fde72a.jpg)
