### ISSUE TITLE
Improve UX when wallet isn't connected

### ISSUE THREAD

**Issue by gpxl-dev** [airswap/airswap-web#153]
Currently it's possible to click the token select but token lists aren't populated due to not having a chain ID yet.

### Discussed in https://github.com/airswap/airswap-web/discussions/144

<div type='discussions-op-text'>

<sup>Originally posted by **wjmelements** August 19, 2021</sup>
Can make it work with fallback jsonrpc; otherwise don't show it.</div>

**Comment by robbestad** [comment]
A related issue is when you connect your wallet but it's not using the Ethereum network. For instance, my metamask is usually connected to BSC, so even after I've connected the UI asks me to connect my wallet and I can't do any swaps. It only works right after I switch over to Ethereum manually.

**Comment by gpxl-dev** [comment]
@robbestad good point - that's captured in #105 but it's an issue I've bumped into a few times. I think it was pending design which is why it hasn't been implemented yet.

**Comment by gpxl-dev** [comment]
Linking to #270
