### ISSUE TITLE
404 Caused with specific page refresh steps on URL change

### ISSUE THREAD

**Issue by asnogordo** [airswap/airswap-web#164]
I was able to cause a 404, and didn't see a similar issue about it.

Reproduce:
1. Go to preview.airswap.io
2. Collapse the 'Welcome to Airswap' pane on the right

This results in the url changing from https://preview.airswap.io/ to https://preview.airswap.io/swap

3. Refresh the page (in browser or F5)
4. 404 error due to https://preview.airswap.io/swap being invalid

![ast_404_error](https://user-images.githubusercontent.com/1376034/130343295-ee8a9994-4cc1-4449-ae8f-b35bb29d4de8.png)

**Comment by asnogordo** [comment]
The url also changes when you click 'Introduction', 'Products', and 'Organization' on the right panel. Same problem occurs (invalid - 404).

**Comment by gpxl-dev** [comment]
Thanks for reporting - this is actually a known issue (#151) but can see that it's not obviously the same!
