### ISSUE TITLE
Add text to README.md

### ISSUE THREAD

**Issue by tesla809** [airswap/airswap-web#2]
Add text to basic training README.md describing:

- Call to action to star the repo
- Link to AirSwap, key resources, AIP-30
- Describe the target audience
- Brief Motivation to create repo (as per AIP-30)
- Motivation for a dev to contribute to the repo
- Overview of the Web App

**Comment by gregplumbly** [comment]
added a draft, will improve...

**Comment by tesla809** [comment]
sweet, let me know if you need me to add anything to the draft beforehand. Or as a Pull Request afterwards.
