### ISSUE TITLE
Test with localstorage disabled

### ISSUE THREAD

**Issue by gpxl-dev** [airswap/airswap-web#200]
Was reading a thread about a site that crashes  on some browser/settings combos because there are no permissions checks wrapped around localstorage use

https://twitter.com/triangulo_dev/status/1437507948595531779?s=19

**Comment by robbestad** [comment]
Here's a good way to check for it: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#feature-detecting_localstorage

What do you want to do when it's unavailable?

**Comment by gpxl-dev** [comment]
I think all of the localStorage functionality we have is non-critical - as long as the core still works (i.e. if errors are thrown they're handled gracefully), then we're okay.
