### ISSUE TITLE
Make sure all buttons have correct border / outline.

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-web#285]
According to jop all buttons with borders need to be darkGrey on hover. Right now outline is the same but maybe we need to differentiate from hover to comply with UI standards.

**Comment by Japlito** [comment]
Borders of buttons or input fields like the token search bar, transaction list/adress, settings wheel, and the menu on the left all have borders #1A1E25. All those 'ghost button's will have #6E7686 as hover color. For the focus/active state they should become blue.

I hope that makes sense, and if there are cases which this doesn't work we should look into how to adjust. But this should work. I'll screenshot some examples.

**Comment by Japlito** [comment]
Inactive

![image](https://user-images.githubusercontent.com/86785367/140278918-0a4263f2-0166-4d02-a6fa-e9e64b03fda2.png)

Hover

![image](https://user-images.githubusercontent.com/86785367/140278961-af86015f-d3a5-4100-9699-861a4e6bbecf.png)

Active/focus

![image](https://user-images.githubusercontent.com/86785367/140279063-de43dc11-386c-4af3-9a42-889ead7b6cc5.png)

**Comment by piersss** [comment]
Yeah, focus is when you tab. This styling can also be used for active.
