### ISSUE TITLE
Bug displaying very small numbers

### ISSUE THREAD

**Issue by agriimony** [airswap/airswap-web#329]
When getting a quote for very small numbers, swapped amount reverts to scientific notation but fails to display the exponent.

This means that the displayed amount is very different from the actual quoted amount:

![image](https://user-images.githubusercontent.com/82473383/140605148-a7564596-b432-4bb4-8d29-42ae29c580e5.png)

![image](https://user-images.githubusercontent.com/82473383/140605151-905cfb8f-9dd0-475d-b054-2ad53f2d7cef.png)

**Comment by gpxl-dev** [comment]
Example mainnet quote for LINK -> ETH - try 0.001 LINK vs 0.0001 LINK
