### ISSUE TITLE
Clicking "unsupported network" should prompt user wallet to switch network

### ISSUE THREAD

**Issue by agriimony** [airswap/airswap-web#335]
When on a wrong network, hover over "Unsupported network" pill highlights the pill, but clicking it does nothing

**Comment by piersss** [comment]
I tested this and switching network works when you're on an unsupported network.

![Screenshot 2022-09-18 at 18 30 02](https://user-images.githubusercontent.com/86911296/190917799-2313c638-c1b2-4654-9d2b-ab695fd63446.png)
