### ISSUE TITLE
Let user remove failed transactions, and clear all transaction

### ISSUE THREAD

**Issue by robbestad** [airswap/airswap-web#363]
It would be nice for a user to be able to remove failed transactions:

![bilde](https://user-images.githubusercontent.com/1560743/141143543-572c510a-1b09-4a55-93a9-2fc4f996d725.png)

**Comment by gpxl-dev** [comment]
Related to #274

**Comment by personnamedmike** [comment]
I added issue #274 , "Transactions List should be able to clear all transactions" into this issue. Will put both issues in the same PR
