### ISSUE TITLE
Wrong text for signer balance low subtext on validator

### ISSUE THREAD

**Issue by gpxl-dev** [airswap/airswap-web#373]
Says something about allowance.

**Comment by francisldn** [comment]
@gpxl-dev, a bit more guidance on this issue would be appreciated, thanks.

**Comment by gpxl-dev** [comment]
Hi @francisldn this should be a very easy one to resolve - looks like it's just swapping the values for the two keys here:

https://github.com/airswap/airswap-web/blob/develop/public/locales/en/translation.json#L138-L139

You can see that the value for "signer_balance_low" mentions allowance (approval), and the allowance text talks about balance.
