### ISSUE TITLE
Add commit hash to UI

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#409]
https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/New-AirSwap-Website?node-id=6788%3A6015

**Comment by 2xAST** [comment]
Should be added in the settings menu. In my view this is not information that needs to be displayed to the user all the time
https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/New-AirSwap-Website?node-id=9932%3A6740

**Comment by Japlito** [comment]
Yeah that's better! I would like to suggest we either put in on top or at the bottom:

In between is not the right place for it - I feel like at the bottom is the best - as it's secondary info and not really a 'setting' 

![image](https://user-images.githubusercontent.com/86785367/172778650-3a26f14c-b3d8-4587-aba0-fe1eefddf5ac.png)

![image](https://user-images.githubusercontent.com/86785367/172778682-fc194565-fca8-4a5f-900a-85c99bff6713.png)

**Comment by 2xAST** [comment]
> Yeah that's better! I would like to suggest we either put in on top or at the bottom:
> 
> In between is not the right place for it - I feel like at the bottom is the best - as it's secondary info and not really a 'setting'
> 
> ![image](https://user-images.githubusercontent.com/86785367/172778650-3a26f14c-b3d8-4587-aba0-fe1eefddf5ac.png)
> 
> ![image](https://user-images.githubusercontent.com/86785367/172778682-fc194565-fca8-4a5f-900a-85c99bff6713.png)

https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/airswap-web?node-id=10127%3A6930
Added github icon, removed external link icon (whole element should be linked), changed date format to ISO 8601, changed font to monospace and extended line to make it its own section
