### ISSUE TITLE
Add support for XDEFI wallet: https://www.xdefi.io/

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#433]

**Comment by GiuntaLucas** [comment]
I check the documentation from xDefi it's seems not possible to use Metamask and xDefi at the same time.
If the user decide to use xDefi by default, they will override the ethereum object to act like metamask.
They are working on that to be able to use both on the same dapp.

So for the moment it's Metamask OR xDefi. To be able to do the switch, the user has to enable/disable the option "Prioritise XDEFI⚠️" from the wallet.
