### ISSUE TITLE
Change text of Metamask button when Metamask is not installed.

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-web#461]
Right now it just fails silently. Solution:

The button should say: _Get Metamask_ and links to https://metamask.io

**Comment by GiuntaLucas** [comment]
@piersss the development is already made by myself, i'm just waiting to have the access to the repo to push my branch, move de ticket and create my pr.

**Comment by piersss** [comment]
> @piersss the development is already made by myself, i'm just waiting to have the access to the repo to push my branch, move de ticket and create my pr.

Ah! No problem. Will update ticket.
