### ISSUE TITLE
Social buttons for mobile

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-web#463]
Social buttons are now hidden on mobile. Mobile design should be updated accordingly.

**Comment by 2xAST** [comment]
https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/New-AirSwap-Website?node-id=9275%3A6819

**Comment by piersss** [comment]
Looks great. 👍

**Comment by piersss** [comment]
Found bug bt @2xAST after this was released to production. Will fix.

 https://github.com/airswap/airswap-web/pull/534#issuecomment-1143739575
