### ISSUE TITLE
Fix New Mobile Site Bug  - WETH to ETH

### ISSUE THREAD

**Issue by Phasor** [airswap/airswap-web#464]
On Rinkeby, when I swap WETH to ETH I get the following bug:

![image](https://user-images.githubusercontent.com/4748572/152573976-eb9af5c0-3e59-4ae3-ab79-ee4e77c17dd6.png)
![image](https://user-images.githubusercontent.com/4748572/152574032-85b9b2bf-45bf-41af-8f76-5690e93adeec.png)

**Comment by robbestad** [comment]
Looked at it. This is a CORS issue from local development. As long as it doesn't appear in production it's not a big issue. To fix it locally you can set up ngrok while developing.
