### ISSUE TITLE
Should never hit "unpredictable gas limit" error

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#523]
The "unpredictable gas limit" error is when MetaMask fails to estimate gas required because the tx simulation fails. Before this happens, the app should be using the `check` function on the swap contract to determine any tx failures ahead of time and display those specific errors to the user.
<img width="570" alt="Screen Shot 2022-04-26 at 2 04 29 PM" src="https://user-images.githubusercontent.com/1601469/165383122-a7304039-6de3-40b1-a4d2-00ca3bf51c03.png">

**Comment by piersss** [comment]
I get this error on firefox when swapping ETH -> DAI. But not on chrome.

**Comment by gpxl-dev** [comment]
Possible to reproduce by trying to swap 1 ETH for DAI on rinkeby.
