### ISSUE TITLE
Make Swap Screen: Expiry selector

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#560]
Figma: https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/airswap-web?node-id=10495%3A9993

![Image](https://user-images.githubusercontent.com/86911296/176759600-405074ab-3e2e-42c7-b20b-f13555d215d6.png)

**Comment by piersss** [comment]
Text input should be any number, max 3 length. Select Input should be minutes, hours, days, maybe weeks?

The API expects an expiry in milliseconds since epoch so output should be the current date plus the amount of time selected by user (ie. 1653807874951).

**Comment by piersss** [comment]
Assigned this ticket to Coltrane.
