### ISSUE TITLE
Fix the mobile menu bug and change the layout to correct design

### ISSUE THREAD

**Issue by Japlito** [airswap/airswap-web#589]
The mobile menu is bugged

It also has incorrect styling. Please take a look at alignment of the menu items. Should be to the left.

Current mobile menu:

![image](https://user-images.githubusercontent.com/86785367/181914467-f1420904-14dd-4802-889d-6ffc156da429.png)

How layout should be:

![image](https://user-images.githubusercontent.com/86785367/181914351-45285c5b-7cd0-461c-93b5-454784ab9105.png)

**Comment by piersss** [comment]
This is on development and we should release this soon.
