### ISSUE TITLE
App might not be passing a provider to the Swap labrary

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#622]
We caught the following while attempting to complete a swap on BSC.

![Untitled](https://user-images.githubusercontent.com/1601469/192907629-b31bbb65-8da4-41c1-923c-6d8a01d6b18d.png)

This implies that a provider is not being passed to the Swap library, so it's attempting to use a default ethers.js provider that doesn't exist (for network "bsc").

**Comment by piersss** [comment]
That is correct. On line 522 and 570 in SwapWidget there's `new Swap(chainId).check(`, no library is passed here.
