### ISSUE TITLE
Impact of long expiry on transaction progress bar

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#647]
While expiry is a good maximum to use on RFQ order progress bars, OTC order expiries are usually much longer. We might be able to cap it at some number of minutes based on some factors, for discussion.

![Image](https://user-images.githubusercontent.com/1601469/198994393-af448a75-e2f0-45a6-8b3b-0e58cd853db0.png)

**Comment by dmosites** [comment]
As discussed on call let's set the progress bar to have a max of 300 seconds.

**Comment by piersss** [comment]
@dmosites max of 300 seconds only for OTC orders then?

**Comment by dmosites** [comment]
For any order: the timeout (as illustrated by the progress bar) would be 300 even if expiry is beyond that. RFQ orders would have a lower expiry of e.g. 170 so their timeout would be 170.
