### ISSUE TITLE
"Make" home screen: Format From and To amounts with K and M to minimize horizontal space

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#650]

**Comment by piersss** [comment]
Do you have an example?

**Comment by dmosites** [comment]
For example:
* 10000 to 10K
* 10000.00001 to 10K
* 12345 to 12.3K
* 1000000 to 1M
* 9876543 to 9.8M
Decimals would have the potential to be longer but this shouldn't be very common:
* 0.001234 to 0.0012
* 0.0000987654 to 0.000098

**Comment by piersss** [comment]
Requirements: Add a `getHumanReadableNumber` to /helpers and add tests for it. Use Don's examples above as tests.
