### ISSUE TITLE
Design Feedback: Make Screen

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#667]
Feedback from @2xAST 

![Image](https://user-images.githubusercontent.com/1601469/201151308-59a44f0d-7c2c-460d-9b6f-448c9313a1cb.png)

- 1/2 remove square corner
- 3 not enough left padding and vertical alignement is off
- 4 vertical alignement is off center
    - maybe instead of “Enter *Token* Amount” just “Enter Amounts”, could be a problem with longer Token Names
- 6 not enough padding left, vertical alignement looks off
- 5 maybe hide the 0.00 when selecting the field
- 7 make this a swap position button

**Comment by dmosites** [comment]
Feedback from @2xAST 

![Image](https://user-images.githubusercontent.com/1601469/201151502-8e011df4-726c-4daa-b88a-a34970020742.png)

- 1/2 Show full token Name and shorten the amount, add hover tooltip to show full amount
- 3 less right padding, align with the numbers, grey color
- 4 more left padding align with the token icons and the FOR
- 5 maybe is redundant as the input field already say “Enter counterparty address”
- Fee Percentage is missing

**Comment by helloitsm3** [comment]
I don't mind helping with this. Can someone assign this to me?

**Comment by coltraneyan** [comment]
> I don't mind helping with this. Can someone assign this to me?
Assigned you!

**Comment by helloitsm3** [comment]
Could you help me move this to in progress? Thanks @coltraneyan
