### ISSUE TITLE
Design Feedback: Swap Screen

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#668]
Feedback from @2xAST 

![Image](https://user-images.githubusercontent.com/1601469/201151922-4e4f9e40-3178-46be-bc6b-5b88b33687d8.png)

- 1 corners should be fully round
    - no feedback after clicking the copy link, maybe add animation that confirms that it was copied
    
    Vertical Alignement of the *i* and the switch position icon
    
- 2/3 vertical alignement of text
- maybe add tooltip with information what it means that it is *for anyone*

**Comment by helloitsm3** [comment]
Is anyone working on this at the moment? I don't mind doing it
