### ISSUE TITLE
Limit decimal places on number inputs to token decimal places

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#678]
https://user-images.githubusercontent.com/86911296/203151347-bc001c16-baa1-4dc1-8631-5efb243a1d30.mov

**Comment by piersss** [comment]
I'll default to this, can improve later if we want.

![Image](https://user-images.githubusercontent.com/86911296/203420764-cc8a3446-81cf-438f-8cbd-e27246da298a.png)

**Comment by 2xAST** [comment]
Color the focus-ring red and add tooltip to the right with information about the amount. After deleting decimals the tooltip will dissappear and the focus-ring should be blue again.
https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/airswap-web?node-id=13189%3A15244&t=2hoAzepk26s6r1p4-4

**Comment by piersss** [comment]
Cool, will implement this in the coming days.
