### ISSUE TITLE
Add translation in Fee modal

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-web#684]
![Image](https://user-images.githubusercontent.com/86911296/204897771-726c9dce-e0bb-47fd-95a1-f39c8ab643da.png)

**Comment by piersss** [comment]
Will ask #content for actual text.

**Comment by 0xtra** [comment]
what about: 

A fee of 0.07% is assessed on each swap to aid the DAO's development and maintenance by our community of contributors. Thank you for supporting AirSwap by using AirSwap!

@dmosites

**Comment by piersss** [comment]
@0xtra Oops, sorry! There is already text for this in the swap feature. 😅 

![Screenshot 2022-12-08 at 22 21 21](https://user-images.githubusercontent.com/86911296/206570009-65c1e963-68f6-44b5-9685-b058a2985455.png)
