### ISSUE TITLE
Allow swaps to be made with arbitrary tokens by address

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#694]
When selecting a token in "Make" mode, user should be able to provide an arbitrary contract address. Once provided, the app should attempt to read ERC20 properties from that contract and enable the user to create a swap from or to the token.

One concern is scams and duplicate tokens. Therefore, once selected, on the "Make" or the "Swap" screens, a token not found in metadata should have a warning icon next to it to indicate that it is unknown and should be verified.

**Comment by 2xAST** [comment]
Is there a way in the app to verify a token, if you got the swap link can you see the token details? 
[Proposal for the warning]( https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/airswap-web?node-id=13418%3A16849&t=h04cUYyDbswdoYwt-4) Focus ring could be red or yellow/orange

**Comment by dmosites** [comment]
If the token is not found in metadata (i.e. it's an unknown token) then clicking on the warning icon could give you the ability to open the etherscan page to inspect the token directly. As for visual treatment, we could have that triangular warning icon immediately left of the token icon and try to make it noticeable but not _very dangerous_ looking. There will be lots of tokens that aren't in the AirSwap metadata so it won't always be a danger, but the user should recognize that they should verify.

**Comment by 2xAST** [comment]
https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/airswap-web?node-id=13446%3A16937&t=mJzsWBeJxCrMQkER-4
like this maybe?
