### ISSUE TITLE
Add loading state when fetching order with unknown token

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-web#710]
![Image](https://user-images.githubusercontent.com/86911296/210078812-c4fcdf67-4ab1-46cf-96b4-0df9aa28cde2.png)

When loading an order with unknown token there should be a loading state. Right now it's just empty until the token gets loaded.

Steps to reproduce:

1. Make order by using an unknown token by manually adding it.
2. Then open your order in incognito mode.

**Comment by piersss** [comment]
Same animation as swap widget:

![Image](https://user-images.githubusercontent.com/86911296/211025308-ac760876-f4cf-4600-b743-d6da1a23c633.png)

**Comment by personnamedmike** [comment]
This feature is already built. Closing issue
