### ISSUE TITLE
State issue switching provider networks with same chainId

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#725]
User reports on `airswap-web-dev` env that "the frontend seems to cache the token list; when I switch back to local node it still has the token list (but can't connect to my account anymore)"

![Image](https://user-images.githubusercontent.com/1601469/214556089-1a23aeeb-5674-4354-b590-1742f48fc678.png)

**Comment by piersss** [comment]
I need to figure out how to run my own node first before I can start fixing this
