### ISSUE TITLE
User cannot list swap due to copy link error

### ISSUE THREAD

**Issue by Warpedpoetic85** [airswap/airswap-web#728]
Maker cannot list swap due to error 'copy failed' when trying to copy swap link on OTC devnet using goerli test network on Android 6.0 OS supported metamask mobile version 5.12.1 
***
![Screenshot_20230128-041344](https://user-images.githubusercontent.com/107268496/215239418-7b2610c5-4ace-4525-acf1-1d85891a5058.jpg)

**Comment by piersss** [comment]
TODO:

1. When error a text field should appear under the copy link button.
2. This text field should contain the whole link. It won't fit on one line so use `text-overflow: ellipsis`.
3. The text field should be preselected. So the user only has to copy it. Use `window.getSelection`.
4. Remove the "copy failed" toast.
