### ISSUE TITLE
Uncaught error causing white screen

### ISSUE THREAD

**Issue by agriimony** [airswap/airswap-web#731]
On https://airswap-web-dev.herokuapp.com/#/make 
Type "." into ETH amount in the "From" field.
Whole screen turns white.

On console:
`Uncaught Error: missing value (argument="value", value=".", code=INVALID_ARGUMENT, version=bignumber/5.7.0)`

**Comment by personnamedmike** [comment]
I opened a PR to fix this issue https://github.com/airswap/airswap-web/pull/771

**Comment by personnamedmike** [comment]
I'm going to close this issue
cc @piersss
