### ISSUE TITLE
Add ability to target a specific server URL via query string

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-web#762]
When set, query from a specific server URL rather than using the Registry.
May need design to indicate the currently targeted server URL.

**Comment by personnamedmike** [comment]
For design

![Screenshot 2023-06-01 at 2 08 41 PM](https://github.com/airswap/airswap-web/assets/90465420/c12ccb6b-5fe2-41e8-8826-8558f03b7781)

**Comment by personnamedmike** [comment]
Discussed with Pierss and we discussed that a design isn't super important, as this is a niche feature that won't be used a whole lot
