### ISSUE TITLE
Add a link to block explorer on Order Completed screen

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-web#770]

**Comment by personnamedmike** [comment]
PR submitted. Needs review

**Comment by personnamedmike** [comment]
Here's a design I used as a placeholder. Do we need a better design?

![Image](https://github.com/airswap/airswap-web/assets/90465420/209919ad-1de9-43b2-9ab5-87cb3b2bf832)

**Comment by Japlito** [comment]
@personnamedmike 

please use this design:

https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/airswap-web?type=design&node-id=4278-6200&t=NWHXDijPEeMM6tV6-4

**Comment by personnamedmike** [comment]
I handed the issue over to Piers since he mentioned he'll take over the ticket, as he's fixing a LastLook bug
