### ISSUE TITLE
Some visual bugs / improvements

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-web#794]
This ticket is for all small visual bugs / improvements:

![Image](https://github.com/airswap/airswap-web/assets/86911296/24bd1c98-2b47-483e-af1e-26cb500b4f03)

![Image](https://github.com/airswap/airswap-web/assets/86911296/e197d476-6f7b-4322-b6cb-3ea68fe8a2d2)

**Comment by 2xAST** [comment]
![Image](https://github.com/airswap/airswap-web/assets/77165803/463caa40-cc78-4eae-afcf-e80e78a41005)

Overlap between _settings_ and _close sidebar_ button on firefox

**Comment by 2xAST** [comment]
![Image](https://github.com/airswap/airswap-web/assets/77165803/52000330-546d-4353-b2b6-dec22d602589)

Should be rounded like the token selector

**Comment by 2xAST** [comment]
Saw some vertical alignement issues on buttons in the chat while people posted their problems. 


![Image](https://github.com/airswap/airswap-web/assets/77165803/ca1a807e-b366-4897-bb86-c99638c5ea67)



![Image](https://github.com/airswap/airswap-web/assets/77165803/21359c4a-dd27-4479-9417-7549e3457479)



![Image](https://github.com/airswap/airswap-web/assets/77165803/b49ba8ff-7904-4853-acdf-fd19bd4b9af4)

**Comment by piersss** [comment]
Moved alignment issues to https://github.com/orgs/airswap/projects/8/views/2?pane=issue&itemId=32545810

**Comment by piersss** [comment]
> ![Image](https://user-images.githubusercontent.com/77165803/250267145-463caa40-cc78-4eae-afcf-e80e78a41005.png)
> 
> Overlap between _settings_ and _close sidebar_ button on firefox

Can not reproduce this on chrome and firefox.
