### ISSUE TITLE
Unpredictable gas limit error when swapping from ETH

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-web#834]
Below in https://github.com/orgs/airswap/projects/8/views/2?pane=issue&itemId=35537867

When swapping from ETH: complete swap:
“unpredictable gas limit”

![Image](https://user-images.githubusercontent.com/86911296/259645183-3e1f778e-f508-48fd-a0f6-6adecaae5719.png)

**Comment by piersss** [comment]
There are 10 variables here:

```
export declare function orderERC20ToParams(order: OrderERC20): [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string
];
```

`["1691698932092","1691699102","0x60d49f8AEEc449599Fe4BfB0289Fca66426bA38b","0x79c950c7446b234a6ad53b908fbf342b01c4d446","15000","0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6","10000000000000","28","0x65952c29a7fb2193dd3e86e51a47fee9317dcea96fce5ffc8d658bf8960860a8","0x2002b6fdc13ae8293fcf492d35685a63a5efd74a810ec95d238dbdd3e340795f"]`

Tried to fill the variables into the contract but it needs 11 variables:

https://goerli.etherscan.io/address/0x99568Ce6c9901097150403B7629CF426B859BC22#writeContract

![Image](https://github.com/airswap/airswap-web/assets/86911296/dec98b7d-30f7-43d2-a9cf-bfa244968262)

**Comment by dmosites** [comment]
The first field `payableAmount` appears to be related to the fact that the function is payable. This means that users can send ether along with this transaction. In this case, the amount of ether sent should equal the senderAmount as verified here: https://github.com/airswap/airswap-protocols/blob/develop/source/wrapper/contracts/Wrapper.sol#L151
