### ISSUE TITLE
Add support for Coinbase wallet

### ISSUE THREAD

**Issue by mikestarrdev** [airswap/airswap-web#917]
to add support for coinbase smart wallets: "To get started, simply bump your Privy SDK version to 1.67.0+ and add Coinbase Wallet to your login flow!" https://warpcast.com/henri/0xf1573447

**Comment by piersss** [comment]
I added coinbase support in the gnosis PR. Perhaps you could test it if you have time.

**Comment by mikestarrdev** [comment]
you're right, it's in the gnosis PR. I'll close out this issue
