### ISSUE TITLE
Design for buttons and inputs hover and active states

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-web#98]
There is no design for hover and active states of all the interactive elements like buttons, inputs and links

**Comment by Japlito** [comment]
@piersss I setup a small doc to collect all elements and their states - can you let me know if there's more elements that you need states on? Thanks

**Comment by Japlito** [comment]
https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/New-AirSwap-Website?node-id=958%3A1600

**Comment by piersss** [comment]
The wallet button also has no active or hover state:
![Screenshot 2021-09-11 at 16 30 27](https://user-images.githubusercontent.com/86911296/132951256-61f66cad-e8d1-4f15-9d3f-1deea73a5712.png)

**Comment by gpxl-dev** [comment]
Relate the hover state for this to #105
